src/Entity/Agents.php
<?php

namespace App\Entity;

use App\Repository\AgentsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AgentsRepository::class)
 */
class Agents
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $phone_number;

    /**
     * @ORM\OneToMany(targetEntity=LaRonde::class, mappedBy="agent", orphanRemoval=true)
     */
    private $laRondes;

    public function __construct()
    {
        $this->laRondes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    /**
     * @return Collection<int, LaRonde>
     */
    public function getLaRondes(): Collection
    {
        return $this->laRondes;
    }

    public function addLaRonde(LaRonde $laRonde): self
    {
        if (!$this->laRondes->contains($laRonde)) {
            $this->laRondes[] = $laRonde;
            $laRonde->setAgent($this);
        }

        return $this;
    }

    public function removeLaRonde(LaRonde $laRonde): self
    {
        if ($this->laRondes->removeElement($laRonde)) {
            // set the owning side to null (unless already changed)
            if ($laRonde->getAgent() === $this) {
                $laRonde->setAgent(null);
            }
        }

        return $this;
    }
}

src/Form/AgentsType.php
<?php

namespace App\Form;

use App\Entity\Agents;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AgentsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'label' => '',
                'label_attr' => ['class' => 'visually-hidden'],
                'attr' => ['placeholder' => 'Nom de l\'agent', 'class' => 'col-md-6 m-2'],
                'row_attr' => ['class' => 'ps-5'],
            ],)
            ->add('prenom', TextType::class, [
                'label' => '',
                'label_attr' => ['class' => 'visually-hidden'],
                'attr' => ['placeholder' => 'Prenom de l\'agent', 'class' => 'col-md-6 m-2'],
                'row_attr' => ['class' => 'ps-5'],
            ],)
            ->add('adresse',null, [
                'label' => '',
                'label_attr' => ['class' => 'visually-hidden'],
                'attr' => ['placeholder' => 'Adresse de l\'agent', 'class' => 'col-md-6 m-2',
                'type' => 'address',],
                'row_attr' => ['class' => 'ps-5'],
                
            ],)
            ->add('phone_number', TextType::class, [
                'label' => '',
                'label_attr' => ['class' => 'visually-hidden'],
                'attr' => ['placeholder' => 'Numero de Téléphone l\'agent', 'class' => 'col-md-6 m-2'],
                'row_attr' => ['class' => 'ps-5'],
                
            ],)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Agents::class,
        ]);
    }
}

src/Controller/AgentsController.php
<?php

namespace App\Controller;

use App\Entity\Agents;
use App\Form\AgentsType;
use App\Repository\AgentsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/agents")
 */
class AgentsController extends AbstractController
{
    /**
     * @Route("/", name="app_agents_index", methods={"GET"})
     */
    public function index(AgentsRepository $agentsRepository): Response
    {
        return $this->render('agents/index.html.twig', [
            'agents' => $agentsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_agents_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AgentsRepository $agentsRepository): Response
    {
        $agent = new Agents();
        $form = $this->createForm(AgentsType::class, $agent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $agentsRepository->add($agent, true);

            return $this->redirectToRoute('app_agents_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('agents/new.html.twig', [
            'agent' => $agent,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_agents_show", methods={"GET"})
     */
    public function show(Agents $agent): Response
    {
        return $this->render('agents/show.html.twig', [
            'agent' => $agent,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_agents_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Agents $agent, AgentsRepository $agentsRepository): Response
    {
        $form = $this->createForm(AgentsType::class, $agent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $agentsRepository->add($agent, true);

            return $this->redirectToRoute('app_agents_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('agents/edit.html.twig', [
            'agent' => $agent,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_agents_delete", methods={"POST"})
     */
    public function delete(Request $request, Agents $agent, AgentsRepository $agentsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$agent->getId(), $request->request->get('_token'))) {
            $agentsRepository->remove($agent, true);
        }

        return $this->redirectToRoute('app_agents_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/agents/_delete_form.html.twig
<form method="post" action="{{ path('app_agents_delete', {'id': agent.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ agent.id) }}">
    <button class="btn">Delete</button>
</form>

templates/agents/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/agents/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Agents{% endblock %}

{% block body %}
    <h1>Edit Agents</h1>

    {{ include('agents/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_agents_index') }}">back to list</a>

    {{ include('agents/_delete_form.html.twig') }}
{% endblock %}

templates/agents/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agents index{% endblock %}

{% block body %}
    <h1>Agents index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Adresse</th>
                <th>Phone_number</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for agent in agents %}
            <tr>
                <td>{{ agent.id }}</td>
                <td>{{ agent.nom }}</td>
                <td>{{ agent.prenom }}</td>
                <td>{{ agent.adresse }}</td>
                <td>{{ agent.phoneNumber }}</td>
                <td>
                    <a href="{{ path('app_agents_show', {'id': agent.id}) }}">show</a>
                    <a href="{{ path('app_agents_edit', {'id': agent.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_agents_new') }}">Create new</a>
{% endblock %}

templates/agents/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Agents{% endblock %}

{% block body %}
    <h1>Create new Agents</h1>

    {{ include('agents/_form.html.twig') }}

    <a href="{{ path('app_agents_index') }}">back to list</a>
{% endblock %}

templates/agents/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agents{% endblock %}

{% block body %}
    <h1>Agents</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ agent.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ agent.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ agent.prenom }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ agent.adresse }}</td>
            </tr>
            <tr>
                <th>Phone_number</th>
                <td>{{ agent.phoneNumber }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_agents_index') }}">back to list</a>

    <a href="{{ path('app_agents_edit', {'id': agent.id}) }}">edit</a>

    {{ include('agents/_delete_form.html.twig') }}
{% endblock %}