src/Entity/LaRonde.php
<?php

namespace App\Entity;

use App\Repository\LaRondeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LaRondeRepository::class)
 */
class LaRonde
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="text")
     */
    private $observation;

    /**
     * @ORM\Column(type="text")
     */
    private $detail;

    /**
     * @ORM\ManyToOne(targetEntity=Agents::class, inversedBy="laRondes", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $agent;

    /**
     * @ORM\ManyToOne(targetEntity=Site::class, inversedBy="laRondes", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $site;

    /**
     * @ORM\ManyToOne(targetEntity=Materiel::class, cascade={"persist"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $materiel;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getObservation(): ?string
    {
        return $this->observation;
    }

    public function setObservation(string $observation): self
    {
        $this->observation = $observation;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(string $detail): self
    {
        $this->detail = $detail;

        return $this;
    }

    public function getAgent(): ?Agents
    {
        return $this->agent;
    }

    public function setAgent(?Agents $agent): self
    {
        $this->agent = $agent;

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(?Site $site): self
    {
        $this->site = $site;

        return $this;
    }

    public function getMateriel(): ?Materiel
    {
        return $this->materiel;
    }

    public function setMateriel(?Materiel $materiel): self
    {
        $this->materiel = $materiel;

        return $this;
    }
}

src/Form/LaRondeType.php
<?php

namespace App\Form;

use App\Entity\LaRonde;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LaRondeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            
            ->add('date_debut', DateTimeType::class, [
                  'label' => 'Date de début',
                  'row_attr' => ['class' => 'ps-5'],
                  ])
            ->add('date_fin', DateTimeType::class, [
                  'label' => 'Date de fin',
                  'row_attr' => ['class' => 'ps-5'],
                  
                  ])
            ->add('observation', TextareaType::class, [
                'label' => 'Observation',
                'label_attr' => ['class' => 'd-block'],
                'attr' => ['class' => 'w-75'],
                'row_attr' => ['class' => 'ps-5'],
                ])
            ->add('detail', TextareaType::class, [
                'label' => 'Début de la Ronde - Chronologie des Missions',
                'label_attr' => ['class' => 'd-block'],
                'attr' => ['class' => 'w-75'],
                'row_attr' => ['class' => 'ps-5'],
                ])
            ->add('agent',AgentsType::class, [
                'label' => 'Renseignement sur l\'Agent/ Rédacteur',
                'label_attr' => ['class' => 'h2 w-75 m-4 p-2 bg-danger text-white'],
                ])
            ->add('site',SiteType::class, [
                'label' => 'Renseignement du site',
                'label_attr' => ['class' => 'h2 bg-danger m-4 w-75 p-2 text-white'],
                ])
            ->add('materiel',MaterielType::class, [
                'label' => 'Récupération Matériel de ronde - Vérification - Début de Mission',
                'label_attr' => ['class' => 'h2 bg-info m-4 p-2 text-white'],
                'attr' => ['class' => 'row m-3',],
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => LaRonde::class,
        ]);
    }
}

src/Controller/LaRondeController.php
<?php

namespace App\Controller;

use App\Entity\LaRonde;
use App\Form\LaRondeType;
use App\Repository\LaRondeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class LaRondeController extends AbstractController
{
    /**
     * @Route("/", name="app_la_ronde_index", methods={"GET"})
     */
    public function index(LaRondeRepository $laRondeRepository): Response
    {
        return $this->render('la_ronde/index.html.twig', [
            'la_rondes' => $laRondeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_la_ronde_new", methods={"GET", "POST"})
     */
    public function new(Request $request, LaRondeRepository $laRondeRepository): Response
    {
        $laRonde = new LaRonde();
        $form = $this->createForm(LaRondeType::class, $laRonde);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
           /* $ag = $laRonde->getAgent();
            $mat = $laRonde->getMateriel();
            $site = $laRonde->getSite();
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($ag);
            $manager->persist($mat);
            $manager->persist($site);
            //$manager->flush();
            $laRonde->setAgent($ag);
            $laRonde->setMateriel($mat);
            $laRonde->setSite($site);
            dd($laRonde);
            $manager->persist($laRonde);
            $manager->flush();*/
           // dd($laRonde->getMateriel());
           //dd($laRonde);
           //$laRonde->setMateriel(null);
           var_dump($laRonde->getMateriel());
            $laRondeRepository->add($laRonde, true);

            return $this->redirectToRoute('app_la_ronde_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('la_ronde/new.html.twig', [
            'la_ronde' => $laRonde,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_la_ronde_show", methods={"GET"})
     */
    public function show(LaRonde $laRonde): Response
    {
        return $this->render('la_ronde/show.html.twig', [
            'la_ronde' => $laRonde,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_la_ronde_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, LaRonde $laRonde, LaRondeRepository $laRondeRepository): Response
    {
        $form = $this->createForm(LaRondeType::class, $laRonde);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $laRondeRepository->add($laRonde, true);

            return $this->redirectToRoute('app_la_ronde_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('la_ronde/edit.html.twig', [
            'la_ronde' => $laRonde,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_la_ronde_delete", methods={"POST"})
     */
    public function delete(Request $request, LaRonde $laRonde, LaRondeRepository $laRondeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$laRonde->getId(), $request->request->get('_token'))) {
            $laRondeRepository->remove($laRonde, true);
        }

        return $this->redirectToRoute('app_la_ronde_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/la_ronde/_delete_form.html.twig
<form method="post" action="{{ path('app_la_ronde_delete', {'id': la_ronde.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ la_ronde.id) }}">
    <button class="btn">Delete</button>
</form>

templates/la_ronde/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/la_ronde/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit LaRonde{% endblock %}

{% block body %}
    <h1>Edit LaRonde</h1>

    {{ include('la_ronde/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_la_ronde_index') }}">back to list</a>

    {{ include('la_ronde/_delete_form.html.twig') }}
{% endblock %}

templates/la_ronde/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Rondes{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12"> 
            <h1>LaRonde index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_fin</th>
                <th>Date_debut</th>
                <th>Observation</th>
                <th>Detail</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for la_ronde in la_rondes %}
            <tr>
                <td>{{ la_ronde.id }}</td>
                <td>{{ la_ronde.dateFin ? la_ronde.dateFin|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ la_ronde.dateDebut ? la_ronde.dateDebut|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ la_ronde.observation }}</td>
                <td>{{ la_ronde.detail }}</td>
                <td>
                    <a href="{{ path('app_la_ronde_show', {'id': la_ronde.id}) }}">show</a>
                    <a href="{{ path('app_la_ronde_edit', {'id': la_ronde.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_la_ronde_new') }}">Create new</a>
        </div>
    </div>
</div>
    
{% endblock %}

templates/la_ronde/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une Ronde{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Ajouter une Ronde</h1>

    {{ include('la_ronde/_form.html.twig') }}

    <a href="{{ path('app_la_ronde_index') }}">back to list</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/la_ronde/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}LaRonde{% endblock %}

{% block body %}
    <h1>LaRonde</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ la_ronde.id }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ la_ronde.dateFin ? la_ronde.dateFin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ la_ronde.dateDebut ? la_ronde.dateDebut|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Observation</th>
                <td>{{ la_ronde.observation }}</td>
            </tr>
            <tr>
                <th>Detail</th>
                <td>{{ la_ronde.detail }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_la_ronde_index') }}">back to list</a>

    <a href="{{ path('app_la_ronde_edit', {'id': la_ronde.id}) }}">edit</a>

    {{ include('la_ronde/_delete_form.html.twig') }}
{% endblock %}